[build-system]

requires = ["setuptools>=42.0.0",
            "setuptools_scm",
            "wheel",
            "extension-helpers",
            "oldest-supported-numpy",
            "cython==0.29.14"]

build-backend = 'setuptools.build_meta'
