version: 2

build:
  os: ubuntu-20.04
  tools:
    python: '{{ cookiecutter.minimum_python_version }}'

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

formats: []
