version: 2

build:
  image: latest
  tools:
    python: '{{ cookiecutter.minimum_python_version }}'

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

formats: []
