version: 2

build:
  image: latest

python:
  version: '{{ cookiecutter.minimum_python_version }}'
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

formats: []
